spring:
  application:
    name: sb3-api-skeleton
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    log-resolved-exception: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
jwt:
  secretKey: your_256_bit_secret_key_here
  expirationTime: 86400000
server:
  port: ${ENV_SERVER_PORT:8080}
